apiVersion: zpa.crossplane.io/v1alpha1
kind: ApplicationSegment
metadata:
  name: example-application
spec:
  forProvider:
    name: AppSeg_Tenant-a
    segmentGroupIDRef:
      name: example-segment
    domainNames:
      - "test.example.com"
    tcpPortRanges:
      - "443"
      - "443"
    serverGroupRefs:
      - name: example-servergroup
  providerConfigRef:
    name: zpa-provider
