apiVersion: zpa.crossplane.io/v1alpha1
kind: ApplicationSegment
metadata:
  name: example-application
spec:
  forProvider:
    customerID: "999999999999999999"
    segmentGroupIDRef:
      name: example-segment
    domainNames:
      - "test.example.com"
    tcpPortRanges:
      - "443"
      - "443"
    udpPortRanges:
      - "443"
      - "443"
  providerConfigRef:
    name: zpa-provider
