apiVersion: zpa.crossplane.io/v1alpha1
kind: SegmentGroup
metadata:
  name: example-segment
spec:
  forProvider:
    customerID: "999999999999999999"
    enabled: true
  providerConfigRef:
    name: zpa-provider
