apiVersion: zpa.crossplane.io/v1alpha1
kind: Server
metadata:
  name: example-server
spec:
  forProvider:
    name: SERVER
    address: "8.8.8.8"
    # you can only use appServerGroupIdsRefs if appServerGroup is setup with dynamicDiscovery: false
    appServerGroupIdsRefs:
      - name: example-servergroup
    enabled: true
  providerConfigRef:
    name: zpa-provider
