// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSegment) DeepCopyInto(out *ApplicationSegment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSegment.
func (in *ApplicationSegment) DeepCopy() *ApplicationSegment {
	if in == nil {
		return nil
	}
	out := new(ApplicationSegment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationSegment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSegmentList) DeepCopyInto(out *ApplicationSegmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationSegment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSegmentList.
func (in *ApplicationSegmentList) DeepCopy() *ApplicationSegmentList {
	if in == nil {
		return nil
	}
	out := new(ApplicationSegmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationSegmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSegmentParameters) DeepCopyInto(out *ApplicationSegmentParameters) {
	*out = *in
	in.CustomApplicationSegmentParameters.DeepCopyInto(&out.CustomApplicationSegmentParameters)
	if in.DomainNames != nil {
		in, out := &in.DomainNames, &out.DomainNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DoubleEncrypt != nil {
		in, out := &in.DoubleEncrypt, &out.DoubleEncrypt
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IPAnchored != nil {
		in, out := &in.IPAnchored, &out.IPAnchored
		*out = new(bool)
		**out = **in
	}
	if in.IsCnameEnabled != nil {
		in, out := &in.IsCnameEnabled, &out.IsCnameEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PassiveHealthEnabled != nil {
		in, out := &in.PassiveHealthEnabled, &out.PassiveHealthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SegmentGroupID != nil {
		in, out := &in.SegmentGroupID, &out.SegmentGroupID
		*out = new(string)
		**out = **in
	}
	if in.TCPPortRanges != nil {
		in, out := &in.TCPPortRanges, &out.TCPPortRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UDPPortRanges != nil {
		in, out := &in.UDPPortRanges, &out.UDPPortRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSegmentParameters.
func (in *ApplicationSegmentParameters) DeepCopy() *ApplicationSegmentParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationSegmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSegmentSpec) DeepCopyInto(out *ApplicationSegmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSegmentSpec.
func (in *ApplicationSegmentSpec) DeepCopy() *ApplicationSegmentSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSegmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSegmentStatus) DeepCopyInto(out *ApplicationSegmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSegmentStatus.
func (in *ApplicationSegmentStatus) DeepCopy() *ApplicationSegmentStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationSegmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomApplicationSegmentParameters) DeepCopyInto(out *CustomApplicationSegmentParameters) {
	*out = *in
	if in.SegmentGroupIDRef != nil {
		in, out := &in.SegmentGroupIDRef, &out.SegmentGroupIDRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.SegmentGroupIDSelector != nil {
		in, out := &in.SegmentGroupIDSelector, &out.SegmentGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomApplicationSegmentParameters.
func (in *CustomApplicationSegmentParameters) DeepCopy() *CustomApplicationSegmentParameters {
	if in == nil {
		return nil
	}
	out := new(CustomApplicationSegmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observation) DeepCopyInto(out *Observation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observation.
func (in *Observation) DeepCopy() *Observation {
	if in == nil {
		return nil
	}
	out := new(Observation)
	in.DeepCopyInto(out)
	return out
}
