/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-zpa/apis/segmentgroup/v1alpha1"
	v1alpha11 "github.com/crossplane-contrib/provider-zpa/apis/servergroup/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ApplicationSegment.
func (mg *ApplicationSegment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SegmentGroupID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SegmentGroupIDRef,
		Selector:     mg.Spec.ForProvider.SegmentGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.SegmentGroupList{},
			Managed: &v1alpha1.SegmentGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SegmentGroupID")
	}
	mg.Spec.ForProvider.SegmentGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SegmentGroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.ServerGroups,
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.ServerGroupRefs,
		Selector:      mg.Spec.ForProvider.ServerGroupSelector,
		To: reference.To{
			List:    &v1alpha11.ServerGroupList{},
			Managed: &v1alpha11.ServerGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServerGroups")
	}
	mg.Spec.ForProvider.ServerGroups = mrsp.ResolvedValues
	mg.Spec.ForProvider.ServerGroupRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Status.AtProvider.ApplicationSegment.SegmentGroupID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Status.AtProvider.ApplicationSegment.SegmentGroupIDRef,
		Selector:     mg.Status.AtProvider.ApplicationSegment.SegmentGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.SegmentGroupList{},
			Managed: &v1alpha1.SegmentGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Status.AtProvider.ApplicationSegment.SegmentGroupID")
	}
	mg.Status.AtProvider.ApplicationSegment.SegmentGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Status.AtProvider.ApplicationSegment.SegmentGroupIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: mg.Status.AtProvider.ApplicationSegment.ServerGroups,
		Extract:       reference.ExternalName(),
		References:    mg.Status.AtProvider.ApplicationSegment.ServerGroupRefs,
		Selector:      mg.Status.AtProvider.ApplicationSegment.ServerGroupSelector,
		To: reference.To{
			List:    &v1alpha11.ServerGroupList{},
			Managed: &v1alpha11.ServerGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Status.AtProvider.ApplicationSegment.ServerGroups")
	}
	mg.Status.AtProvider.ApplicationSegment.ServerGroups = mrsp.ResolvedValues
	mg.Status.AtProvider.ApplicationSegment.ServerGroupRefs = mrsp.ResolvedReferences

	return nil
}
